# Generated by Django 3.2.16 on 2022-10-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('priorite', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['priorite'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('priorite', models.FloatField(default=0)),
                ('desc', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('cree', models.DateTimeField(auto_now_add=True)),
                ('modif', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('estCours', models.BooleanField(default=True)),
                ('estActionCampus', models.BooleanField(default=True)),
                ('estActionCollege', models.BooleanField(default=True)),
                ('estActionLycee', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priorite'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('priorite', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['priorite'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField()),
                ('appelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.appelle')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('fichier', models.FileField(upload_to='file')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cours')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.groupe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.matiere'),
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.ManyToManyField(to='home.Classe'),
        ),
        migrations.AddField(
            model_name='appelle',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.groupe'),
        ),
    ]
