# Generated by Django 4.0.6 on 2022-08-21 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210807_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='cree',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='estCours',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='cours',
            name='modif',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.ManyToManyField(to='home.classe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cours',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='priorite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.matiere'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='priorite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='priorite',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField()),
                ('appelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.appelle')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('fichier', models.FileField(upload_to='file')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cours')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.groupe'),
        ),
        migrations.AddField(
            model_name='appelle',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.groupe'),
        ),
    ]
